### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by zhaobey** [CaptainCN/MiniExcelReader#2]
I found a defect in your code:
`Cell* Sheet::getCell(int row, int col)`
`{`
 `if (row < _dimension.firstRow || row > _dimension.lastRow)`
  `return nullptr;`
  `if (col < _dimension.firstCol || col > _dimension.lastRow)`
   `return nullptr;`
   `return _cells[toIndex(row, col)];`
`}`

you can see that that check sentence : if (col < _dimension.firstCol || col > _dimension.lastRow)
It should be if (col < _dimension.firstCol || col > _dimension.**lastCol**), right ?

If you create an excel file which col number is bigger than row number, you can find this defect.

**Comment by qcdong2016** [comment]
Yes. It's Drunk code. You can create a pr.
